### ISSUE TITLE
an idea to add to the repo

### ISSUE THREAD

**Issue by shayan15sa** [bmwant/pypod#2]
hello misha. i'm shayan. i'm trying to make an app in python for open music or something like that. i have an repo in my github for that that's fully empty. i just got the idea. i wanna make an app for online music streaming. the idea is use github servers to upload music and mp3 files in a repo and tag for that. then the client app uses github api to find repos that have that tag. then play the mp3 that's in that repo. i was making ui for that with gtk but that was tuff. so i just start searching in github for new repo about python music player and i found your repo. i'll fork your repo and try to add that feature to it.  i'll need your help. so it would be awsome if i can have a way to contact you,email ,discord , or something else.

**Comment by bmwant** [comment]
Hi @shayan15sa, thanks for your interest of the project. Feel free to fork a repository and implement any desired feature on top of this code. Unfortunately, I don't have enough capacity to directly participate in your project, but would be able to help you by commenting on the issues within this repo or you can mention `@bmwant` me on your fork

**Comment by shayan15sa** [comment]
Thanks for respond!
